[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'

[healthcheck]
path = '/health'
interval = 10
timeout = 5
retries = 3
